routes/web.php
Route::get('/home', 'HomeController@index')->name('home');

Route::group(["prefix" => "admin", "namespace" => "Admin", 'middleware' => 'auth:admin'], function () {

    /********* User Management */
    Route::get('/users', 'UserController@index')->name('user.index');
    Route::get('/users/create', 'UserController@create')->name('user.create');
    Route::get('/users/edit/{reference_id}', 'UserController@edit')->name('user.edit');
    Route::post('/users/destroy/{reference_id}', 'UserController@destroy')->name('user.destroy');
    Route::post('/users/store', 'UserController@store')->name('user.store');
    Route::POST('/users/update/{reference_id}', 'UserController@update')->name('user.update');
    /*********role and permission */
    Route::resource('/roles', 'RoleController');
    Route::post('/roles/destroy/{reference_id}', 'RoleController@destroy')->name('roles.destroy');
    Route::resource('/permissions', 'PermissionController');
    Route::post('/permissions/destroy/{reference_id}', 'PermissionController@destroy')->name('permissions.destroy');
    /*******************user profile */
    Route::post('/user-profile-password-update', 'UserProfileController@updatepassword')->name('userpassword.update');
    Route::resource('/user-profile', 'UserProfileController');

    /************************Catgory*********/
    Route::resource('/category', 'CategoryController');
    Route::POST('/category/update/{reference_id}', 'CategoryController@update')->name('category.update');
    Route::post('/category/destroy/{reference_id}', 'CategoryController@destroy')->name('category.destroy');

    Route::get('/checkfordeleted/{keyword?}', 'CategoryController@checkfordeleted')->name('category.checkfordeleted');
    Route::get('/restoredeleted/{keyword?}', 'CategoryController@restoredeleted')->name('category.restoredeleted');
    Route::get('/search-category/{keyword?}', 'CategoryController@searchCategory')->name('search.category');


    /************************SubCatgory*********/
    Route::resource('/subcategory', 'SubCategoryController');
    Route::POST('/subcategory/update/{reference_id}', 'SubCategoryController@update')->name('subcategory.update');
    Route::post('/subcategory/destroy/{reference_id}', 'SubCategoryController@destroy')->name('subcategory.destroy');

    Route::get('/checkfordeletedsubcategory/{keyword?}', 'SubCategoryController@checkfordeleted')->name('subcategory.checkfordeletedsubcategory');
    Route::get('/restoredeletedsubcategory/{keyword?}', 'SubCategoryController@restoredeleted')->name('subcategory.restoredeletedsubcategory');
    Route::get('/search-subcategory/{keyword?}', 'SubCategoryController@searchSubCategory')->name('search.subcategory');
    /************************Product*********/
    Route::resource('/product', 'ProductController');
    Route::POST('/product/update/{reference_id}', 'ProductController@update')->name('product.update');
    Route::post('/product/destroy/{reference_id}', 'ProductController@destroy')->name('product.destroy');
    Route::get('getproduct/{id}', 'ProductController@getProduct')->name('get.product');


    Route::get('/checkfordeletedproduct/{keyword?}', 'ProductController@checkfordeleted')->name('product.checkfordeletedproduct');
    Route::get('/restoredeletedproduct/{keyword?}', 'ProductController@restoredeleted')->name('product.restoredeletedproduct');

    /************************Brand*********/
    Route::resource('/brand', 'BrandController');
    Route::POST('/brand/update/{reference_id}', 'BrandController@update')->name('brand.update');
    Route::post('/brand/destroy/{reference_id}', 'BrandController@destroy')->name('brand.destroy');

    Route::get('/checkfordeletedbrand/{keyword?}', 'BrandController@checkfordeleted')->name('brand.checkfordeletedbrand');
    Route::get('/restoredeletedbrand/{keyword?}', 'BrandController@restoredeleted')->name('brand.restoredeletedbrand');
    Route::get('/search-brand/{keyword?}', 'BrandController@searchBrand')->name('search.brand');

    /************************ProductReview*********/
    Route::resource('/productreview', 'ProductReviewController');
    Route::POST('/productreview/update/{reference_id}', 'ProductReviewController@update')->name('productreview.update');
    Route::post('/productreview/destroy/{reference_id}', 'ProductReviewController@destroy')->name('productreview.destroy');

    Route::get('/checkfordeletedproductreview/{keyword?}', 'ProductReviewController@checkfordeletedproductreview')->name('productreview.checkfordeletedproductreview');
    Route::get('/restoredeletedproductreview/{keyword?}', 'ProductReviewController@restoredeletedproductreview')->name('productreview.restoredeletedproductreview');
    Route::get('/search-product/{keyword?}', 'ProductReviewController@searchProduct')->name('search.product');
    /************************Order*********/
    Route::resource('/order', 'OrderController');
    Route::get('get/order', 'OrderController@getOrder');
    /************************Prescription*********/
    Route::resource('/prescription', 'PrescriptionController');
    Route::get('search-product/{keyword?}', 'PrescriptionController@searchProduct')->name('prescription.product');
    Route::post('/prescription-order', 'PrescriptionController@addprescriptionorder')->name('prescription.order');
    //  Route::POST('/product/update/{reference_id}', 'ProductController@update')->name('product.update');
    //  Route::post('/product/destroy/{reference_id}','ProductController@destroy')->name('product.destroy');

    //  Route::get('/checkfordeletedproduct/{keyword?}', 'ProductController@checkfordeleted')->name('product.checkfordeletedproduct');
    //  Route::get('/restoredeletedproduct/{keyword?}', 'ProductController@restoredeleted')->name('product.restoredeletedproduct');
    /************************SearchData*********/
    Route::resource('/searchdata', 'SearchDataController');
    //   Route::get('search-product/{keyword?}', 'PrescriptionController@searchProduct')->name('prescription.product');
    //   Route::post('/prescription-order','PrescriptionController@addprescriptionorder')->name('prescription.order');

});
Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');
Route::get('/verify', 'VerifyController@getVerigy')->name('getVerify');
Route::post('/verify', 'VerifyController@postVerify')->name('verify');
// Route::get('/admin','AdminController@index');
Route::prefix('admin')->group(function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
});
// Route::get('/getemail', function() {
//     if (1==1) {
//         $notifiable =  Auth::user();
//         $order = Auth::user()->orders()->latest()->first();
//         return FacadesResponse::view('admin.emails/orders/orderConfirmation',compact('notifiable','order'));
//     }

// });
Auth::routes(['verify' => true]);
Route::get('/', 'Frontend\IndexController@index')->name('showIndex');
Route::get('/category/{reference_id}/product', 'Frontend\IndexController@categoryproduct')->name('category.product');
Route::get('/product/details/{slug}', 'Frontend\ProductController@productdetails')->name('product.details');
Route::get('/add-to-cart/{quantity}/{product_id}', 'Frontend\ProductController@getAddToCart')->name('product.addToCart');
Route::get('/reduce-by-one/{product_id}', 'Frontend\ProductController@getReduceByOne')->name('product.removeFromCart');
Route::get('/remove-product-from-cart/{product_id}', 'Frontend\ProductController@removeProductFromCart')->name('product.removeProductFromCart');
Route::get('/shopping-cart', 'Frontend\ProductController@getCart')->name('product.shoppingCart');
Route::get('/shopping-checkout', 'Frontend\OrderController@checkout')->name('shopping.checkout');
Route::get('/order-summary/{order_id}', 'Frontend\OrderController@getRecentOrder')->name('order.success');
Route::get('/order-failed/{order_id}', 'Frontend\OrderController@getRecentFailedOrder')->name('order.failed');
Route::get('/order-open/{order_id}', 'Frontend\OrderController@getRecentOpenOrder')->name('order.open');
Route::post('/store/order', 'Frontend\OrderController@store')->name('order.store');
Route::get('/user-profile', 'Frontend\UserProfileController@index')->name('user.profile');
Route::post('/store/address', 'Frontend\UserProfileController@storeaddress')->name('saveuser.address');
Route::post('/user/getExistingUser', 'Frontend\UserProfileController@getExistingUser')->name('check.user');
Route::post('/store/prescription', 'Frontend\OrderController@storePrescription')->name('store.prescription');
Route::post('/productsearch/fetch', 'Frontend\ProductController@searchfetch')->name('search.fetch');
Route::post('/update-password', 'Frontend\UserProfileController@updatepassword')->name('update.password');

Route::get('/payment', 'PaytmController@pay');
Route::post('/payment/status', 'PaytmController@paymentCallback');
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('login.google');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/verify-phone', 'VerifyController@getVerify')->name('getverify');
Route::post('/verify-phone', 'VerifyController@postVerify')->name('verify');
Route::get('/update-phone', 'Frontend\UserProfileController@updatePhone')->name('update.phone');
Route::post('/update-phone', 'Frontend\UserProfileController@saveMobilenumber')->name('save.phone');

Route::post('loginWithOtp', 'Frontend\UserProfileController@loginWithOtp')->name('loginWithOtp');
Route::get('/loginWithOtp', 'Frontend\UserProfileController@loginWithOtpView');


Route::post('checkmobilenumber', 'Frontend\UserProfileController@checkmobilenumber');

app/Models/Brand.php
<?php

namespace App\Models;

use App\Admin;
use App\Traits\BrandTrait;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use BrandTrait;
    protected $table = 'brands';

    public static function boot()
    {
        parent::boot();
    }

    public function getCreateInfoAttribute()
    {
       return $createInfo = "".' ' .$this->created_at->diffForHumans().' '.'By'.' '.Admin::where('id', $this->created_by)->pluck('name')->first();
    }
    public function getUpdateInfoAttribute()
    {
       return $updateInfo = "".' ' .$this->updated_at->diffForHumans().' '.'By'.' '.Admin::where('id', $this->updated_by)->pluck('name')->first();
    }
}

app/Http/Controllers/Admin/ProductReviewController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductReview\StoreProductReviewRequest;
use App\MedicinePharma\Repositories\Product\ProductInterface;
use App\MedicinePharma\Repositories\ProductReview\ProductReviewInterface;
use Exception;

class ProductReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   
    private $product;
    private $productreview;
    
    public function __construct(ProductInterface $product,ProductReviewInterface $productreview){
       $this->product = $product;
       $this->productreview = $productreview;
    }

    public function index()
    {
        $productreviews = $this->productreview->getAll();
        return view('admin.productreview/index',compact('productreviews'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.productreview.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductReviewRequest $request)
    {
       
        try {
            $saveproductreview = $this->productreview->store($request);
            return redirect()->route('productreview.index');
        }catch (Exception $ex) {
            dd($ex->getMessage());
            abort(400, "Somehting went wrong");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $productreview = $this->productreview->find($id);
        return view('admin.productreview/edit',compact('productreview'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateproductreview = $this->productreview->update($request,$id);
        return redirect()->route('productreview.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $deleteproductreview = $this->productreview->delete($id);
        }catch(\Exception $e){
            return redirect()->route('productreview.index')->with('danger', $e->getMessage());
        }
        return redirect()->route('productreview.index');
    }
    public function checkfordeletedproductreview($keyword=null)
    {
        $checktrait = $this->checkfordeletedproductreview($keyword);
        return  $checktrait;
    }
    public function restoredeletedproductreview($keyword=null)
    {
        $restoretrait = $this->restoredeletedproductreview($keyword);
        return  $restoretrait;
    }
    public function searchProduct($keyword=null)
    {
        $products = $this->productreview->searchProduct($keyword);
        $productArray=[];
        foreach ($products as $productkey=>$product){
            $productArray[$productkey]['id']=$product->id;
            $productArray[$productkey]['text']=$product->name;
        }
        return $productArray;
    }
}

resources/views/admin/productreview/create.blade.php
@extends('adminlte::page')

@section('title', 'Create ProductReview')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Create ProductReview</div>
                    <div class="panel-body">
                        <a href="{{ route('productreview.index') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        {{-- @include('admin.alertMessage') --}}

                        {!! Form::open(['route' => 'productreview.store', 'class' => 'form-horizontal','method'=>'POST','id'=>'productReviewRegistrationForm','enctype'=>"multipart/form-data"]) !!}

                       
                     
                        <div class="form-group {{ $errors->has('product_id') ? 'has-error' : ''}}">
                                <label for="product" class = 'col-md-4 control-label'>Product</label>
                                <div class="col-md-6">
                                <select id="product_id" class="selectpicker form-control product-select2"
                                data-show-subtext="true" name="product_id" data-live-search="true" title="">
                                </select>

                                </div>
                                <small id="helpId" class="text-muted">Help text</small>
                         </div>
                         <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                            <label for="name" class = 'col-md-4 control-label'>Comment</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="name" id="name" value="{{ old('name')}}">
                                {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
                            </div>
                        </div>
                       

                        <div class="form-group {{ $errors->has('image') ? 'has-error' : ''}}">
                            <label for="image" class = 'col-md-4 control-label'>Product Image</label>
                            <div class="col-md-6">
                                <input type="file" class="form-control" name="image[]" id="image" multiple>
                                {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
                            </div>
                        </div>
                        <div class="col-lg-12">

                        </div>
                        <div class="form-group {{ $errors->has('rating') ? 'has-error' : ''}}">
                            <label for="rating" class = 'col-md-4 control-label'>Rating</label>
                            <div class="col-md-6">
                            <input id="rating" name="rating" type="radio" class="" value="1" {{ old('is_active') ? 'checked' : '' }}/>1
                            <input id="rating" name="rating" type="radio" class="" value="2" {{ old('is_active') ? 'checked' : '' }}/>2
                            <input id="rating" name="rating" type="radio" class="" value="3" {{ old('is_active') ? 'checked' : '' }}/>3
                            <input id="rating" name="rating" type="radio" class="" value="4" {{ old('is_active') ? 'checked' : '' }}/>4
                            <input id="rating" name="rating" type="radio" class="" value="5" {{ old('is_active') ? 'checked' : '' }}/>5
                            </div>
                        </div>
                        
                        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                            <button type="submit" class="btn btn-success">Save</button>
                        </div>

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
         $(document).ready(function () {

            $(".product-select2").select2({
                ajax: {
                    url: function (params) {
                        return "{{route('search.product').'/'}}" + params.term;
                    },
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {q: params.term, };
                    },
                    processResults: function (data, params) {
                        return {results: data};
                    },
                    cache: true
                },
                minimumInputLength: 3,
            });

      
        })
          </script>
@endpush
@yield('js')

resources/views/admin/productreview/index.blade.php
@extends('adminlte::page')

@section('title', 'ProductReview Master')
@section('css')
<style>
.mt-2 {
    margin-top: 1rem!important;
}
</style>
@endsection
@section('content')

<section>
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <!-- /.box -->
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">ProductReview Listing</h3>
            </div>
            <!-- The Modal -->
           


            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12">
                        <a href="{{route('productreview.create')}}">
                            <button class="btn btn-success pull-right">
                                    Create <span class="badge badge-primary">new</span>
                            </button>
                        </a>
                            <button class="btn btn-success pull-left">
                                    Total ProductReview <span class="badge badge-primary">{{count($productreviews)}}</span>
                            </button>
                    </div>
                </div>
                <div class="row">&nbsp;</div>
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Product Name</th>
                  <th>Comment</th>
                  <th>Image</th>
                  <th>Rating</th>
                  <th>Create Info</th>
                  <th>Update Info</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($productreviews as $productreview)
                    @php $imagearray = explode(',',$productreview->image); @endphp
                    <tr class="appenddata">
                      <td class="text-capitalize prod_brand" data-brandname="{{$productreview->product->name??""}}">{{$productreview->product->name??""}}</td>
                      <td class="text-capitalize prod_name" data-name="{{$productreview->name??""}}">{{$productreview->name??""}}</td>
                      <td class="image prod_image" data-image=" {{$productreview->image}}">
                        @foreach($imagearray as $key=>$prodimage)
                        <div class="col-sm-2">
                        <div class="user-block">
                             <img alt="{{$productreview->name}}" src="{{URL::asset('storage/uploads/productreview/thumbnails/'.$prodimage)}}" class="img-circle img-bordered-sm" >
                        </div>
                        </div>
    
                        @endforeach
                        </td>
                        <td class="text-capitalize prod_name" >
                          <div class="rating">
                            @for($i = 0; $i < 5; $i++)
                                <span><i class="fa fa-star{{ $productreview->rating <= $i ? '-o' : '' }}"></i></span>
                            @endfor
                        </div>
                        </td>
                        <td data-createdinfo="{{$productreview->create_info?$productreview->create_info:'' }}">{{$productreview->create_info?$productreview->create_info:'' }}</td>
                    <td data-updateinfo="{{$productreview->update_info?$productreview->update_info:'' }}">{{$productreview->update_info?$productreview->update_info:'' }}</td>
                        <td class="prod_id" data-id="{{$productreview->id}}">
                          <div class="btn-group btn-group-sm">
                            
                                
                              <a href="{{ route('productreview.edit',$productreview->id) }}" class="edit-model btn btn-warning btn-sm " ><i class="fa fa-edit"></i></a>
                                  <button class="delete-model btn btn-danger btn-sm " type="button" onclick="deleteProductReview({{ $productreview->id }})">
                                      <i class="fa fa-trash"></i>
                                  </button>
                                  <form id="delete-form-{{ $productreview->id }}" action="{{ route('productreview.destroy',$productreview->id) }}" method="POST" style="display: none;">
                                      <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                  </form>
                          </div>
                          </td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>Product Name</th>
                  <th>Comment</th>
                  <th>Image</th>
                  <th>Rating</th>
                  <th>Create Info</th>
                  <th>Update Info</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
</section>
@endsection
@push('js')
<script>
    $(function () {
      $('#example1').DataTable({
        'paging'      : true,
        'lengthChange': true,
        'searching'   : true,
        'ordering'    : true,
        'info'        : true,
        'autoWidth'   : false,
        "scrollX": true
      })
    })
  </script>

  <script type="text/javascript">
  function deleteProductReview(id) {
   const swalWithBootstrapButtons = Swal.mixin({
  customClass: {
    confirmButton: 'btn btn-success',
    cancelButton: 'btn btn-danger'
  },
  buttonsStyling: false
})

swalWithBootstrapButtons.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  type: 'warning',
  showCancelButton: true,
  confirmButtonText: 'Yes, delete it!',
  cancelButtonText: 'No, cancel!',
  reverseButtons: true
}).then((result) => {
  if (result.value) {
    event.preventDefault();
      document.getElementById('delete-form-'+id).submit();
  } else if (
    /* Read more about handling dismissals below */
    result.dismiss === Swal.DismissReason.cancel
  ) {
    swalWithBootstrapButtons.fire(
      'Cancelled',
      'Your imaginary file is safe :)',
      'error'
    )
  }
})
  }
  
  </script>
@endpush
@yield('js')

resources/views/admin/productreview/show.blade.php
@extends('adminlte::page')

@section('title', 'Product Show')
@section('css')
<style>
    .well img{
display: inline-block;
}
    </style>
@endsection
@section('content')

<section>
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <!-- /.box -->
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">ProductReview Listing</h3>
            </div>


            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12">
                        <a href="{{route('product.create')}}">
                            <button class="btn btn-success pull-right">
                                    Create <span class="badge badge-primary">new</span>
                            </button>
                        </a>
                            <button class="btn btn-success pull-left">
                                    Total ProductReview <span class="badge badge-primary">{{count($product)}}</span>
                            </button>
                    </div>
                </div>
                <div class="row">&nbsp;</div>

            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
</section>
@endsection
@push('js')
<script>
    $(function () {
      $('#example1').DataTable({
        'paging'      : true,
        'lengthChange': true,
        'searching'   : true,
        'ordering'    : true,
        'info'        : true,
        'autoWidth'   : false,
        "scrollX": true
      })
    })
  </script>

  <script type="text/javascript">
  function deleteProduct(id) {
   const swalWithBootstrapButtons = Swal.mixin({
  customClass: {
    confirmButton: 'btn btn-success',
    cancelButton: 'btn btn-danger'
  },
  buttonsStyling: false
})

swalWithBootstrapButtons.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  type: 'warning',
  showCancelButton: true,
  confirmButtonText: 'Yes, delete it!',
  cancelButtonText: 'No, cancel!',
  reverseButtons: true
}).then((result) => {
  if (result.value) {
    event.preventDefault();
      document.getElementById('delete-form-'+id).submit();
  } else if (
    /* Read more about handling dismissals below */
    result.dismiss === Swal.DismissReason.cancel
  ) {
    swalWithBootstrapButtons.fire(
      'Cancelled',
      'Your imaginary file is safe :)',
      'error'
    )
  }
})
  }</script>
@endpush
@yield('js')