routes/web.php
Route::get('/home', 'HomeController@index')->name('home');

Route::group(["prefix" => "admin", "namespace" => "Admin", 'middleware' => 'auth:admin'], function () {

    /********* User Management */
    Route::get('/users', 'UserController@index')->name('user.index');
    Route::get('/users/create', 'UserController@create')->name('user.create');
    Route::get('/users/edit/{reference_id}', 'UserController@edit')->name('user.edit');
    Route::post('/users/destroy/{reference_id}', 'UserController@destroy')->name('user.destroy');
    Route::post('/users/store', 'UserController@store')->name('user.store');
    Route::POST('/users/update/{reference_id}', 'UserController@update')->name('user.update');
    /*********role and permission */
    Route::resource('/roles', 'RoleController');
    Route::post('/roles/destroy/{reference_id}', 'RoleController@destroy')->name('roles.destroy');
    Route::resource('/permissions', 'PermissionController');
    Route::post('/permissions/destroy/{reference_id}', 'PermissionController@destroy')->name('permissions.destroy');
    /*******************user profile */
    Route::post('/user-profile-password-update', 'UserProfileController@updatepassword')->name('userpassword.update');
    Route::resource('/user-profile', 'UserProfileController');

    /************************Catgory*********/
    Route::resource('/category', 'CategoryController');
    Route::POST('/category/update/{reference_id}', 'CategoryController@update')->name('category.update');
    Route::post('/category/destroy/{reference_id}', 'CategoryController@destroy')->name('category.destroy');

    Route::get('/checkfordeleted/{keyword?}', 'CategoryController@checkfordeleted')->name('category.checkfordeleted');
    Route::get('/restoredeleted/{keyword?}', 'CategoryController@restoredeleted')->name('category.restoredeleted');
    Route::get('/search-category/{keyword?}', 'CategoryController@searchCategory')->name('search.category');


    /************************SubCatgory*********/
    Route::resource('/subcategory', 'SubCategoryController');
    Route::POST('/subcategory/update/{reference_id}', 'SubCategoryController@update')->name('subcategory.update');
    Route::post('/subcategory/destroy/{reference_id}', 'SubCategoryController@destroy')->name('subcategory.destroy');

    Route::get('/checkfordeletedsubcategory/{keyword?}', 'SubCategoryController@checkfordeleted')->name('subcategory.checkfordeletedsubcategory');
    Route::get('/restoredeletedsubcategory/{keyword?}', 'SubCategoryController@restoredeleted')->name('subcategory.restoredeletedsubcategory');
    Route::get('/search-subcategory/{keyword?}', 'SubCategoryController@searchSubCategory')->name('search.subcategory');
    /************************Product*********/
    Route::resource('/product', 'ProductController');
    Route::POST('/product/update/{reference_id}', 'ProductController@update')->name('product.update');
    Route::post('/product/destroy/{reference_id}', 'ProductController@destroy')->name('product.destroy');
    Route::get('getproduct/{id}', 'ProductController@getProduct')->name('get.product');


    Route::get('/checkfordeletedproduct/{keyword?}', 'ProductController@checkfordeleted')->name('product.checkfordeletedproduct');
    Route::get('/restoredeletedproduct/{keyword?}', 'ProductController@restoredeleted')->name('product.restoredeletedproduct');

    /************************Brand*********/
    Route::resource('/brand', 'BrandController');
    Route::POST('/brand/update/{reference_id}', 'BrandController@update')->name('brand.update');
    Route::post('/brand/destroy/{reference_id}', 'BrandController@destroy')->name('brand.destroy');

    Route::get('/checkfordeletedbrand/{keyword?}', 'BrandController@checkfordeleted')->name('brand.checkfordeletedbrand');
    Route::get('/restoredeletedbrand/{keyword?}', 'BrandController@restoredeleted')->name('brand.restoredeletedbrand');
    Route::get('/search-brand/{keyword?}', 'BrandController@searchBrand')->name('search.brand');

    /************************ProductReview*********/
    Route::resource('/productreview', 'ProductReviewController');
    Route::POST('/productreview/update/{reference_id}', 'ProductReviewController@update')->name('productreview.update');
    Route::post('/productreview/destroy/{reference_id}', 'ProductReviewController@destroy')->name('productreview.destroy');

    Route::get('/checkfordeletedproductreview/{keyword?}', 'ProductReviewController@checkfordeletedproductreview')->name('productreview.checkfordeletedproductreview');
    Route::get('/restoredeletedproductreview/{keyword?}', 'ProductReviewController@restoredeletedproductreview')->name('productreview.restoredeletedproductreview');
    Route::get('/search-product/{keyword?}', 'ProductReviewController@searchProduct')->name('search.product');
    /************************Order*********/
    Route::resource('/order', 'OrderController');
    Route::get('get/order', 'OrderController@getOrder');
    /************************Prescription*********/
    Route::resource('/prescription', 'PrescriptionController');
    Route::get('search-product/{keyword?}', 'PrescriptionController@searchProduct')->name('prescription.product');
    Route::post('/prescription-order', 'PrescriptionController@addprescriptionorder')->name('prescription.order');
    //  Route::POST('/product/update/{reference_id}', 'ProductController@update')->name('product.update');
    //  Route::post('/product/destroy/{reference_id}','ProductController@destroy')->name('product.destroy');

    //  Route::get('/checkfordeletedproduct/{keyword?}', 'ProductController@checkfordeleted')->name('product.checkfordeletedproduct');
    //  Route::get('/restoredeletedproduct/{keyword?}', 'ProductController@restoredeleted')->name('product.restoredeletedproduct');
    /************************SearchData*********/
    Route::resource('/searchdata', 'SearchDataController');
    //   Route::get('search-product/{keyword?}', 'PrescriptionController@searchProduct')->name('prescription.product');
    //   Route::post('/prescription-order','PrescriptionController@addprescriptionorder')->name('prescription.order');

});
Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');
Route::get('/verify', 'VerifyController@getVerigy')->name('getVerify');
Route::post('/verify', 'VerifyController@postVerify')->name('verify');
// Route::get('/admin','AdminController@index');
Route::prefix('admin')->group(function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
});
// Route::get('/getemail', function() {
//     if (1==1) {
//         $notifiable =  Auth::user();
//         $order = Auth::user()->orders()->latest()->first();
//         return FacadesResponse::view('admin.emails/orders/orderConfirmation',compact('notifiable','order'));
//     }

// });
Auth::routes(['verify' => true]);
Route::get('/', 'Frontend\IndexController@index')->name('showIndex');
Route::get('/category/{reference_id}/product', 'Frontend\IndexController@categoryproduct')->name('category.product');
Route::get('/product/details/{slug}', 'Frontend\ProductController@productdetails')->name('product.details');
Route::get('/add-to-cart/{quantity}/{product_id}', 'Frontend\ProductController@getAddToCart')->name('product.addToCart');
Route::get('/reduce-by-one/{product_id}', 'Frontend\ProductController@getReduceByOne')->name('product.removeFromCart');
Route::get('/remove-product-from-cart/{product_id}', 'Frontend\ProductController@removeProductFromCart')->name('product.removeProductFromCart');
Route::get('/shopping-cart', 'Frontend\ProductController@getCart')->name('product.shoppingCart');
Route::get('/shopping-checkout', 'Frontend\OrderController@checkout')->name('shopping.checkout');
Route::get('/order-summary/{order_id}', 'Frontend\OrderController@getRecentOrder')->name('order.success');
Route::get('/order-failed/{order_id}', 'Frontend\OrderController@getRecentFailedOrder')->name('order.failed');
Route::get('/order-open/{order_id}', 'Frontend\OrderController@getRecentOpenOrder')->name('order.open');
Route::post('/store/order', 'Frontend\OrderController@store')->name('order.store');
Route::get('/user-profile', 'Frontend\UserProfileController@index')->name('user.profile');
Route::post('/store/address', 'Frontend\UserProfileController@storeaddress')->name('saveuser.address');
Route::post('/user/getExistingUser', 'Frontend\UserProfileController@getExistingUser')->name('check.user');
Route::post('/store/prescription', 'Frontend\OrderController@storePrescription')->name('store.prescription');
Route::post('/productsearch/fetch', 'Frontend\ProductController@searchfetch')->name('search.fetch');
Route::post('/update-password', 'Frontend\UserProfileController@updatepassword')->name('update.password');

Route::get('/payment', 'PaytmController@pay');
Route::post('/payment/status', 'PaytmController@paymentCallback');
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('login.google');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('/verify-phone', 'VerifyController@getVerify')->name('getverify');
Route::post('/verify-phone', 'VerifyController@postVerify')->name('verify');
Route::get('/update-phone', 'Frontend\UserProfileController@updatePhone')->name('update.phone');
Route::post('/update-phone', 'Frontend\UserProfileController@saveMobilenumber')->name('save.phone');

Route::post('loginWithOtp', 'Frontend\UserProfileController@loginWithOtp')->name('loginWithOtp');
Route::get('/loginWithOtp', 'Frontend\UserProfileController@loginWithOtpView');


Route::post('checkmobilenumber', 'Frontend\UserProfileController@checkmobilenumber');

app/Models/Brand.php
<?php

namespace App\Models;

use App\Admin;
use App\Traits\BrandTrait;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use BrandTrait;
    protected $table = 'brands';

    public static function boot()
    {
        parent::boot();
    }

    public function getCreateInfoAttribute()
    {
       return $createInfo = "".' ' .$this->created_at->diffForHumans().' '.'By'.' '.Admin::where('id', $this->created_by)->pluck('name')->first();
    }
    public function getUpdateInfoAttribute()
    {
       return $updateInfo = "".' ' .$this->updated_at->diffForHumans().' '.'By'.' '.Admin::where('id', $this->updated_by)->pluck('name')->first();
    }
}

app/Models/SearchKeyword.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class SearchKeyword extends Model
{
    protected $table = 'search_data';

    public static function boot()
    {
        parent::boot();
    }
    public function getCreateInfoAttribute()
    {
       return $createInfo = "".' ' .$this->created_at->diffForHumans().' ';
    }
    public function getUpdateInfoAttribute()
    {
       return $updateInfo = "".' ' .$this->updated_at->diffForHumans().' ';
    }

    public function getUserDataAttribute()
    {
        return $userdata = "".' ' .User::where('id', $this->user_id)->pluck('name')->first().' ';
    }
}

app/Http/Controllers/Admin/SearchDataController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\MedicinePharma\Repositories\Brand\BrandInterface;
use App\MedicinePharma\Repositories\SearchData\SearchDataInterface;
use App\Traits\BrandTrait;
use Brian2694\Toastr\Toastr;
use Exception;

class SearchDataController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $searchdata;
    public function __construct(SearchDataInterface $searchdata){
        $this->searchdata = $searchdata;
    }
    public function index()
    {
        $searchdatas = $this->searchdata->getAll();
        return view('admin.searchdata/index',compact('searchdatas'));
    }
}

resources/views/admin/searchdata/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Brand')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Create Brand</div>
                    <div class="panel-body">
                        <a href="{{ route('brand.index') }}" title="Back"><button class="btn btn-warning btn-xs"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        {{-- @include('admin.alertMessage') --}}

                        {!! Form::open(['route' => 'brand.store', 'class' => 'form-horizontal','method'=>'POST','id'=>'brandRegistrationForm','enctype'=>"multipart/form-data"]) !!}

                        <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                            <label for="name" class = 'col-md-4 control-label'>Brand Name</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="name" id="name">
                                {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
                            </div>
                        </div>
                        <div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
                            <label for="description" class = 'col-md-4 control-label'>Brand description</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="description" id="description">
                                {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
                            </div>
                        </div>
                        <div class="form-group {{ $errors->has('is_active') ? 'has-error' : ''}}">
                            <label for="is_active" class = 'col-md-4 control-label'>Active</label>
                            <div class="col-md-6">
                            <input id="is_active" name="is_active" type="checkbox" class="" value="1" {{ old('is_active') ? 'checked' : '' }}/>
                            </div>
                        </div>
                       
                        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                            <button type="submit" class="btn btn-success">Save</button>
                        </div>


                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>



    <script>
            $(function () {
              //Datemask dd/mm/yyyy
              $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
              //Datemask2 mm/dd/yyyy
              $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
              //Money Euro
              $('[data-mask]').inputmask()

              //Date range picker
              $('#reservation').daterangepicker()
              //Date range picker with time picker
              $('#reservationtime').daterangepicker({ timePicker: true, timePickerIncrement: 30, locale: { format: 'MM/DD/YYYY hh:mm A' }})
              //Date range as a button
              $('#daterange-btn').daterangepicker(
                {
                  ranges   : {
                    'Today'       : [moment(), moment()],
                    'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
                    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                    'This Month'  : [moment().startOf('month'), moment().endOf('month')],
                    'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                  },
                  startDate: moment().subtract(29, 'days'),
                  endDate  : moment()
                },
                function (start, end) {
                  $('#daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
                }
              )

              //Date picker
              $('#datepicker').datepicker({
                autoclose: true
              })

              //iCheck for checkbox and radio inputs
              $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass   : 'iradio_minimal-blue'
              })
              //Red color scheme for iCheck
              $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                checkboxClass: 'icheckbox_minimal-red',
                radioClass   : 'iradio_minimal-red'
              })
              //Flat red color scheme for iCheck
              $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass   : 'iradio_flat-green'
              })

              //Colorpicker
              $('.my-colorpicker1').colorpicker()
              //color picker with addon
              $('.my-colorpicker2').colorpicker()

              //Timepicker
              $('.timepicker').timepicker({
                showInputs: false
              })
            })

            $("#brandRegistrationForm").submit(function(e){
                e.preventDefault();
                var name = $("#name").val();
                $.ajax({
                    url:"/admin/checkfordeletedbrand/"+name,
                    dataType:"json",
                    success: function (data) {
                        console.log("adasd"+data);
                        if(name === data.name)
                        {
                            const swalWithBootstrapButtons = Swal.mixin({
                            customClass: {
                                confirmButton: 'btn btn-success',
                                cancelButton: 'btn btn-danger'
                            },
                            buttonsStyling: false
                            })

                            swalWithBootstrapButtons.fire({
                            title: 'Given Brand Name is already Exist (Deleted)!',
                            text: "Would Like to restored?",
                            type: 'warning',
                            showCancelButton: true,
                            confirmButtonText: 'Yes, restore it!',
                            cancelButtonText: 'No, cancel!',
                            reverseButtons: true
                            }).then((result) => {
                            if (result.value) {
                                $.ajax({
                                url:"/admin/restoredeletedbrand/"+name,
                                dataType:"json",
                                success: function (data) {
                                    // toastr.error("Category Restored Sucessfully.");
                                    toastr.success("<br /><br /><button type='button' id='confirmationRevertYes' class='btn btn-danger'>Ok</button>",'Brand Restored Sucessfully!',
                                        {
                                            closeButton: false,
                                            allowHtml: true,
                                            positionClass:'toast-top-center',
                                            onShown: function (toast) {
                                                $("#confirmationRevertYes").click(function(){
                                                    window.location.href = "{{ route('brand.index')}}";
                                                });
                                                }
                                        });
                                        setTimeout(function(){
                                            window.location.href = "{{ route('brand.index')}}";
                                        }, 2000);

                                }
                                });
                            } else if (
                                /* Read more about handling dismissals below */
                                result.dismiss === Swal.DismissReason.cancel
                            ) {
                                swalWithBootstrapButtons.fire(
                                'Cancelled',
                                'Your cancled :)',
                                'error'
                                )
                            }
                            })
                        } else {
                            e.preventDefault();
                            document.getElementById('brandRegistrationForm').submit();
                        }
                    }
                });
            });
          </script>
@endpush
@yield('js')

resources/views/admin/searchdata/index.blade.php
@extends('adminlte::page')

@section('title', 'Search Data Master')

@section('content')

<section>
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <!-- /.box -->
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Search Data Listing</h3>
            </div>


            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12">

                            <button class="btn btn-success pull-left">
                                    Total Search <span class="badge badge-primary">{{count($searchdatas)}}</span>
                            </button>
                    </div>
                </div>
                <div class="row">&nbsp;</div>
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Keyword</th>
                  <th>User</th>
                  <th>Create Info</th>
                  <th>Update Info</th>
                  {{-- <th>Action</th> --}}
                </tr>
                </thead>
                <tbody>
                    @foreach($searchdatas as $value)
                    <tr>
                    <td class="text-capitalize">{{$value->search_keyword??""}}</td>
                    <td>{{!empty($value->user_data)?$value->user_data:''}} </td>
                    <td>{{$value->create_info?$value->create_info:'' }}</td>
                    <td>{{$value->update_info?$value->update_info:'' }}</td>
                    {{-- <td>
                        <div class="btn-group btn-group-sm">
                            <a href="{{ route('brand.edit',$brand->id) }}" class="edit-model btn btn-warning btn-sm " ><i class="fa fa-edit"></i></a>
                                <button class="delete-model btn btn-danger btn-sm " type="button" onclick="deleteBrand({{ $brand->id }})">
                                    <i class="fa fa-trash"></i>
                                </button>
                                <form id="delete-form-{{ $brand->id }}" action="{{ route('brand.destroy',$brand->id) }}" method="POST" style="display: none;">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                </form>
                        </div>
                        </td> --}}
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>Keyword</th>
                  <th>User</th>
                  <th>Create Info</th>
                  <th>Update Info</th>
                    {{-- <th>Action</th> --}}
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
</section>
@endsection
@push('js')
<script>
    $(function () {
      $('#example1').DataTable({
        'paging'      : true,
        'lengthChange': true,
        'searching'   : true,
        'ordering'    : true,
        'info'        : true,
        'autoWidth'   : false,
        "scrollX": true
      })
    })
  </script>

  <script type="text/javascript">
  function deleteBrand(id) {
   const swalWithBootstrapButtons = Swal.mixin({
  customClass: {
    confirmButton: 'btn btn-success',
    cancelButton: 'btn btn-danger'
  },
  buttonsStyling: false
})

swalWithBootstrapButtons.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  type: 'warning',
  showCancelButton: true,
  confirmButtonText: 'Yes, delete it!',
  cancelButtonText: 'No, cancel!',
  reverseButtons: true
}).then((result) => {
  if (result.value) {
    event.preventDefault();
      document.getElementById('delete-form-'+id).submit();
  } else if (
    /* Read more about handling dismissals below */
    result.dismiss === Swal.DismissReason.cancel
  ) {
    swalWithBootstrapButtons.fire(
      'Cancelled',
      'Your imaginary file is safe :)',
      'error'
    )
  }
})
  }</script>
@endpush
@yield('js')